language: python

python:
  - 2.7

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-dev python-fuse python-pyxattr python-pylibacl linux-libc-dev

install: make

script:
  - make test
  - sudo make test
